{
 "title": "Flow Dashboard",
 "description": "The Glorious Datasboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "search" },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Invocations in progress",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "function_invocations_in_progress{service=~\"$service_name\", function!=\"GET_/metrics\"}",
     "legendFormat": "{{service}}  {{function}}"
    }
   ]
  },
  {
   "title": "Exceptions Raised in 5s",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(exceptions_total{function!~\"GET_/metrics\", service=~\"$service_name\"}[5s])",
     "legendFormat": "{{service}}  {{function}}"
    }
   ]
  },
  {
   "title": "Timeline",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=~\"$service_name\"} |~ \"$search\"[$__interval]))"
    }
   ]
  },
  {
   "title": "Service Logs",
   "type": "table",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"$service_name\"} |~ \"$search\" | json | flow_name=~\".+\""
    }
   ]
  }
 ]
}