{
 "title": "Flow Dashboard",
 "description": "The Glorious Datasboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "search" },
   {
    "name": "flow",
    "label": "Flow",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Completed Flow Runtime",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(flow_processing_time_bucket{flow=\"$flow\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flow_status_total{flow=\"$flow\", status=\"COMPLETED\"}) / sum(flow_status_total{flow=\"$flow\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Timeline",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({flow_name=~\"$flow\" } |~ \"$search\"[$__auto]) ) by (level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Service Logs",
   "type": "table",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{flow_name=~\"$flow\"} |~ \"$search\" | json"
    }
   ]
  }
 ]
}